### ISSUE TITLE
Voetnoten niet correct - Duinen en Lage land Texel

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#19]

**Comment by KevinvdBosch** [comment]
De validatie laat ook fouten in de voetnoten zien. Dit zit dus in de inhoud

![afbeelding](https://user-images.githubusercontent.com/27193836/124103461-96b41800-da61-11eb-8d73-bf71a9013778.png)

**Comment by zoeheerema** [comment]
Kruisverwijzing ingevoegd naar voetnoot 6
