### ISSUE TITLE
Voetnoot bij opschrift weergeven in PlanoView

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/Natura2000inDSO#2]
voetnoot achter opschrift zetten

**Comment by KevinvdBosch** [comment]
Voetnoten worden nu in de tekst getoond

**Comment by KevinvdBosch** [comment]
![afbeelding](https://user-images.githubusercontent.com/27193836/124105597-a92f5100-da63-11eb-8ec7-a3fff5c3f822.png)
