### ISSUE TITLE
Inhoud: opsomming verkeerd - Groote Peel

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#21]
Artikel 1, pagina 4. Opsomming dient in letters in plaats van cijfers.

**Comment by KevinvdBosch** [comment]
Artikel 1 is onderverdeeld in lid 1 en 2. Hierin staan geen opsommingen. Er staat wel een opsomming in Artikel 2, maar dat zijn al letters zoals in het aanleverbesluit
