### ISSUE TITLE
Meinweg - kaart laadt niet in Planoview

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#217]

**Comment by RoderikTukker** [comment]
Hetzelfde geldt voor Doggersbank, Klaverbank en Savelsbos.

**Comment by thomas-idgis** [comment]
De oplossing voor Meinweg is dat er maar 1 werkingsgebied geannoteerd kan worden per lid.
Doggersbank en Klaverbank vallen buiten de kaartranden.
Savelsbos error is neem ik aan een issue opzich.
