### ISSUE TITLE
Hyperlink bijlage C - Groote Peel

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#23]
Als je op de link/verwijzing naar de motivering klikt dan verwijst de link naar {terug naar bijlage C en niet naar deze verwijzing” Motivering van het besluit op basis van de binnengekomen zienswijzen”

**Comment by KevinvdBosch** [comment]
Hyperlink was verkeerd aangemaakt in het Word document waardoor in Word zelf de eigenschap interne verwijzing kreeg.
Link werkt nu
