### ISSUE TITLE
Inhoud: Artikel 2 - Groote Peel

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#24]
Op pagina 4. De vogelsoorten bij c. en de trekkende vogelsoorten bij d. zijn samengevoegd en worden onder d. gezet, is dat de bedoeling omdat het om hetzelfde artikel zowel bij c als bij d gaat? Alleen het lid verschilt eerste lid/tweede lid.

**Comment by KevinvdBosch** [comment]
Dit was een bug bij het omzetten. Tabellen zitten nu wel goed in artikel 2:

![afbeelding](https://user-images.githubusercontent.com/27193836/123976452-71ba9900-d9be-11eb-93af-0baa64dba663.png)
