### ISSUE TITLE
Voetnoten niet correct - Groote Peel

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#25]
Voetnoot (pag.11) par. 4.2.1 Habitatrichtlijn: habitattypen (bijlage I[footnoteRef:10]) tekst die ernaar verwijst ontbreekt “Bijlagen I en II laatstelijk aangepast op 20 november 2006, Richtlijn 2006/105/EG, PbEG L 363, 20.12.2006, p. 368-405 (zie ook rectificatie PbEG L 80, 21.3.2007, p. 15).”

Par. 5.1 (pag. 14): het laatste alineablok wordt er verwezen naar een voetnoot {nr.7} “…..gebiedsdoelstellingen per habitattype en per (vogel)soort7”, stuk tekst die er naar verwijst ontbreekt:

**Comment by KevinvdBosch** [comment]
De voetnoot in paragraaf 4.2.1 is een bug, die moet opgelost worden.

De verwijzing naar voetnoot 7 in paragraaf 5.1 is een fout in de inhoud. Hier staat alleen een 7 als superscript, niet als voetnoot.

**Comment by KevinvdBosch** [comment]
paragraaf 4.2.1: voetnoot is verwerkt in de tekst

![afbeelding](https://user-images.githubusercontent.com/27193836/124102562-c31b6480-da60-11eb-9ce8-f86059ecf487.png)
