### ISSUE TITLE
Engbertsdijksvenen - vogelrichtlijngebied (Artikel 2) laadt niet op de kaart

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#256]

**Comment by HermanAssink** [comment]
Waarneming: Bij het selecteren van artikel 2 wordt het gebied van "Uiterwaarden Zwarte water" in de kaart getoond. Dat is natuurlijk niet goed.

**Comment by KevinvdBosch** [comment]
In het Word document blijken ook de verkeerde annotaties geplaatst te zijn:
![afbeelding](https://user-images.githubusercontent.com/27193836/130762320-3171725a-0cc5-465b-a772-9274c538f810.png)
