### ISSUE TITLE
Opschrift: ontbreken van hyperlinks naar besluiten - Sneekermeergebied

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#26]
In de handleiding staat hoe deze links moeten worden opgenomen zodat deze met de conversie worden overgenomen

**Comment by KevinvdBosch** [comment]
Hyperlinks zijn toegevoegd. Was een bug in de programmatuur

![afbeelding](https://user-images.githubusercontent.com/27193836/123971947-be9c7080-d9ba-11eb-9fae-e60bee1654a2.png)

**Comment by KevinvdBosch** [comment]
Nieuwe versie ge-upload, opmaak is aangepast
