### ISSUE TITLE
Cursief weergeven van tekst in voetnoten

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#261]
In 4.3.1 staan in de betreffende voetnoten de begrippen ‘moerasspirea’ en ‘droge bosranden’ niet cursief, terwijl ze wel als zodanig worden aangeleverd:

Oosterschelde (voetnoot 16)
Weerter- en Budelerbergen en Ringselven (voetnoot 18)
Deurnsche Peel & Mariapeel (voetnoot 14)
Oeffelter Meent (voetnoot 15)
Sint Jansberg (voetnoot 14)
Zeldersche Driessen (voetnoot 13)
Boschhuizerbergen (voetnoot 12)
Maasduinen (voetnoot 19)
Sarsven en De Banen (voetnoot 15)
In 4.3.1 staan in de betreffende voetnoten de begrippen ‘moerasspirea’ en ‘droge bosranden’ nog steeds niet cursief.

**Comment by KevinvdBosch** [comment]
Dat was een bug in onze converter. Bovenstaande besluiten zijn opnieuw geladen in de viewer met de bugfix
