### ISSUE TITLE
Kaarten in Bijlage A: Weerter- en Budelerbergen en Ringselven

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#262]
De kaarten worden in de juiste volgorde aangeleverd, maar in Planoview worden ze omgewisseld, dit terwijl er al meerdere keren is geprobeerd de volgorde juist te krijgen.

**Comment by KevinvdBosch** [comment]
Zo te zien zijn beide afbeeldingen in Word binnen één alinea geplaatst (zie screenshot hieronder). In Word is het erg moeilijk om dan de volgorde te bepalen. De 2e afbeelding heet onder water namelijk image1.png (wat de volgorde in de viewer kan verklaren). Ik ga een test doen door iedere afbeelding in een eigen alinea te plaatsen. Dan zou het wel goed door moeten komen.

![afbeelding](https://user-images.githubusercontent.com/27193836/136202948-9dfbd280-f354-4da3-8a70-f48bb4359a23.png)

**Comment by KevinvdBosch** [comment]
De plaatjes in afzonderlijke alinea's in Word zetten lijkt het probleem te verhelpen. Aangepaste bestanden zijn gemaild.
![afbeelding](https://user-images.githubusercontent.com/27193836/136205327-2d8478e5-5fa0-4883-9407-3870e9252fa5.png)
