### ISSUE TITLE
Duinen Vlieland: paragraaf 5.3: tabel H2140 blijft zichtbare tabelranden hebben, ik krijg dit niet weggewerkt helaas

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#263]

**Comment by KevinvdBosch** [comment]
Onder water bleek dat voor de individuele cellen de randen inderdaad verwijderd waren, maar op tabel niveau stonden ze nog wel aangegeven.
Word document aangepast en opnieuw geladen in de viewer.
