### ISSUE TITLE
Duinen Terschelling - in Planoview wordt de kaart van Vlieland weergeven i.p.v. Terschelling.

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#264]

**Comment by KevinvdBosch** [comment]
Artikel 3 lid 2 lijkt geannoteerd te staan met het Natura-2000 gebied van Vlieland
![afbeelding](https://user-images.githubusercontent.com/27193836/136922507-03da7f4a-f27f-4496-9cec-56f46eb12e46.png)
