### ISSUE TITLE
Witte en Zwarte Brekken & Deelen & Leekstermeergebied - tabelranden in Artikel 1 blijven zichtbaar

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#268]
Kevin kan jij kijken of dit onderwater opgelost kan worden?

**Comment by KevinvdBosch** [comment]
Dit was wederom een andere notatie door Word onder water die nog niet geïmplementeerd was. Het bestand is opnieuw geladen

**Comment by RoderikTukker** [comment]
Kan je dit ook aanpassen bij Deelen en Leekstermeergebied alsjeblieft, dank!

**Comment by RoderikTukker** [comment]
En ik zie het zelfde probleem nu ook bij besluit Lieftinghsbroek voorbij komen.

**Comment by RoderikTukker** [comment]
Drouwenerzand heeft ook zichtbare tabelranden bij de besluitartikelen.

**Comment by RoderikTukker** [comment]
Springendal & Dal van de Mosbeek heeft dit ook.

**Comment by RoderikTukker** [comment]
Bergvennen & Brecklenkampse Veld ook.

**Comment by RoderikTukker** [comment]
Aamsveen & Arkemheen helaas ook...

**Comment by KevinvdBosch** [comment]
De volgende besluiten zijn ook aangepast en opnieuw geladen:
- Deelen
- Leekstermeergebied
- Lieftinghsbroek
- Drouwenerzand
- Springendal & Dal van de Mosbeek
- Bergvennen & Brecklenkampse Veld
- Aamsveen
- Arkemheen

**Comment by RoderikTukker** [comment]
Dank voor het herladen van de besluiten hierboven Kevin!
De volgende hebben ook nog zichtbare tabelranden...:
- Wooldse Veen
- Loevestein, Pompveld & Kornsche BoezemK
- Kennemerland-Zuid
- Polder Zeevang
- Oostelijke Vechtplassen
- Meijendel & Berkheide
- Boezems Kinderdijk
- Donkse Laagten
- Oude Maas
- Oudeland van Strijen
- Brabantse Wal
- Loonse en Drunense Duinen & Leemkuilen
- Vlakte van de Raan
- De Wieden
- Elperstroomgebied

**Comment by KevinvdBosch** [comment]
Bovenstaande 15 besluiten zijn opnieuw geladen
