### ISSUE TITLE
Opschrift: Gebreken in opschrift - Sneekermeergebied

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#27]
· Onderstrepingen moeten worden verwijderd stonden bij spaties, Kevin heeft dit weggehaald. · Nummer eerste Stcr. Mist nog steeds. Kevin geeft aan dat dit niet in de input zit. Stan corrigeert dit en voegt het opschrift toe zodat het nog een keer getest kan worden. In het opschrift komen bullits voor maar dat moet een doorlopend opschrift worden · Nummer tweede Stcr. moet als volgt: “Staatscourant 4458 van 14 maart 2011” voorgesteld eerst het jaartal en dan “,” en kenmerk. Dit wordt opgelost in de content. · Datum wijzigingsbesluit klopt niet dit wordt opgelost in de content.

**Comment by zoeheerema** [comment]
Nummer staatscourant aangepast, datum wijzingingsbesluit aangepast. Opmaak opschrift aangepast (doorlopend ipv opsomming)

**Comment by KevinvdBosch** [comment]
Nieuwe versie staat klaar om te controleren
