### ISSUE TITLE
Inhoud: Opsommingsfouten artikel 1 en ontbreken van artikel 2 lid 3 - Sneekermeergebied

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#28]
· Opsomming is in cijfers i.p.v. letters fout van Kevin, heeft hij voor Sneekermeer herstelt. 
· Vogelsoorten staan verkeerd opgesomd Er is een lijstje met 5 vogelsoorten dat onder sub c moet komen en x en nu onder “e”

komen. Kevin zoekt uit of dit in de content zit (stijlen) of IDgis - digitalisering 

Artikel 2: 
· Lid 3 mist in zijn geheel lid 3 zit niet in het aanleverbestand. Checken of het in het aanleverbestand zit en toevoegen en opnieuw testen

**Comment by KevinvdBosch** [comment]
Vogelsoorten zijn nu correct opgesomd. Dat ging mis bij het inlezen.

Zoals gemeld in een [eerdere opmerking](https://github.com/IDgis/Natura2000inDSO/issues/28#issue-933697832) vermeld zit Artikel 2 Lid 3 niet in het aanleverbestand

**Comment by zoeheerema** [comment]
Artikel 2 lid 3 toegevoegd

**Comment by KevinvdBosch** [comment]
artikel 2 lid 3 is niet opgemaakt als lid en komt nu als tekst in lid 2 te staan

![afbeelding](https://user-images.githubusercontent.com/27193836/125241081-4bb0c500-e2eb-11eb-8fd6-d0384a74464f.png)

**Comment by zoeheerema** [comment]
Artikel 2 lid 3 is in de opmaak nu toegevoegd als zelfstandig lid

**Comment by KevinvdBosch** [comment]
Nieuwe versie staat klaar om gecontroleerd te worden, hierin is artikel 2 lid 3 verwerkt
