### ISSUE TITLE
Nota van toelichting: Paragrafen aangeduid als hoofdstukken - Sneekermeergebied

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#29]
· De paragrafen in de nota v. toelichting worden aangeduid als hoofdstuk terwijl dit paragrafen zijn Kevin Michiel, Roderik en Stan zoeken uit of dit in de instructie zit (content) of digitalisering door IDgis

**Comment by KevinvdBosch** [comment]
Hoofdstuk en paragraaf aanduiding zijn nu overgenomen zoals ze voorkomen in het aanleverbesluit om verwarring te voorkomen.

![afbeelding](https://user-images.githubusercontent.com/27193836/123972134-e095f300-d9ba-11eb-8076-6fac2f291715.png)
