### ISSUE TITLE
Typo bij Naardermeer

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/Natura2000inDSO#3]
tekst "landenLandelijke" bij Naardermeer: Bijlage B / Hoofdstuk B.4 / Paragraaf B.4.1 / tabel H7140B

**Comment by KevinvdBosch** [comment]
![afbeelding](https://user-images.githubusercontent.com/27193836/122344507-28426680-cf47-11eb-92a1-c105e1c5e6a0.png)
