### ISSUE TITLE
Nota van toelichting: fout in voetnoten - Sneekermeergebied

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#30]
De voetnoten beginnen bij elke paragraaf opnieuw vanaf 1. (dit is onhandig i.v.m. terugverwijzingen naar eerdere voetnoten) dit is een issue van vorige keer. Tekst moet dubbel worden opgenomen in de voetnoten. Hoofdstuk 4: · §4.2.2 bevat een verdwaalde voetnoot onderaan. Staat een nummer 1 en staat geen tekst. In het originele bestand is het niet. Kevin zoekt het uit.

**Comment by KevinvdBosch** [comment]
De verdwaalde voetnoot komt in verband met hergebruik naar een eerdere voetnoot. Om dit op te lossen moet hier een losse voetnoot voor worden gemaakt in plaats van een eerdere gemaakte voetnoot te hergebruiken

**Comment by KevinvdBosch** [comment]
De validatie van het sjabloon laat ook inderdaad een lege voetnoot zien. Dit zit dus in de inhoud:

![afbeelding](https://user-images.githubusercontent.com/27193836/124092767-80a15a00-da57-11eb-9fb8-e9d7a134b981.png)

Deze voetnoot verwijst naar deze lege locatie in het document:
![afbeelding](https://user-images.githubusercontent.com/27193836/124092845-93b42a00-da57-11eb-95ee-7d6eabae9987.png)

**Comment by zoeheerema** [comment]
Voetnoot verwijderd en opnieuw ingevoegd
