### ISSUE TITLE
Bijlagen: Appendix - Sneekermeergebied

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#33]
Appendix: · Woord ‘BIJLAGE’ voor appendix kan weg staat niet in het aanleverbestand. Kevin zoekt dit uit. Het komt maar een paar keer voor dat er een appendix/bijlage is. in het origineel bestand zit appendix erin. De lijn is zoveel mogelijk het origineel bestand volgen. · De voetnoten in de appendix bevatten de cijfers 42 en 43, kunnen ook weg er staat voetnoot 1 en 1 en dan 42 en 43. Kevin zoekt dit uit. De voetnoten lopen door paragraaf C in het origineel bestand.

**Comment by KevinvdBosch** [comment]
Woord 'BIJLAGE' is verwijderd voor de appendix. Ging mis bij het omzetten

![afbeelding](https://user-images.githubusercontent.com/27193836/123972327-09b68380-d9bb-11eb-8a59-a941d3622084.png)
