### ISSUE TITLE
Inhoud: artikel 1 lid 3 ontbreekt  - Alde Feanen

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#34]

**Comment by KevinvdBosch** [comment]
Artikel 1 lid 3 ontbreekt inderdaad aangezien deze in de aanlevering niet als lid is opgemaakt, maar als gewone tekst.
In het navigatievenster van Word zie je dat hij eveneens ontbreekt:

![afbeelding](https://user-images.githubusercontent.com/27193836/124094725-5355ab80-da59-11eb-8650-4846cde9e3b3.png)
