### ISSUE TITLE
Nota van toelichting: voetnoten verkeerd opgenomen - Alde Feanen

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#35]
Introductie: · Eerste voetnoot bevat een spatie in de tekst onder kopje nota van toelichting wordt het wettelijk kader weeergegeven. Voetnoot met een verwijzing. De voetnoot is er gek ingezet. Moet achter 2009 spatie voetnoot. Dit is een content fout.Stan en Roderik corrigeren dat. 

§3.2: · Laatste alinea: voetnoot 8 is verkeerd opgenomen in de tekst voetnoot 3 en was voetnoot nr 8. Er staat een 8 als superscript bij. Roderik en Stan passen dit in de content aan. 

§4.2.1: · Voetnoot in de titel is niet verwerkt

§4.3.1: · De voetnoten a & b in de tabel zijn verkeerd opgenomen en staan nu als ‘Xa’ & ‘Yb’ Zie §4.3.2 voor een voorbeeld over de terugverwijzing naar eerdere voetnoten.

**Comment by KevinvdBosch** [comment]
§3.2: Dit zit inderdaad in de inhoud: 

![afbeelding](https://user-images.githubusercontent.com/27193836/124095411-eee71c00-da59-11eb-8315-6f50eb7b6a6a.png)

§4.2.1: Dit moet opgelost worden in de conversie

§4.3.1: Dit zit in de content. Bij a & b is alleen de grootte van het lettertype veranderd en ze zijn niet opgenomen als superscript:

![afbeelding](https://user-images.githubusercontent.com/27193836/124096100-906e6d80-da5a-11eb-95f9-009898c12734.png)
![afbeelding](https://user-images.githubusercontent.com/27193836/124096179-a419d400-da5a-11eb-8fc6-c7f91f9b233f.png)

**Comment by KevinvdBosch** [comment]
§4.2.1: voetnoot is nu ook in de titel verwerkt:

![afbeelding](https://user-images.githubusercontent.com/27193836/124100400-bc8bed80-da5e-11eb-8abb-13147907b913.png)
