### ISSUE TITLE
Bijlagen: opmaak en voetnoten - Alde Feanen

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#36]
· De opmaak van de tabellen uit Bijlage B zijn niet goed meegenomen · Onder tabellen waar enkel een voetnoot (a) is opgenomen moeten deze als opsomming (met tab) worden opgenomen

**Comment by KevinvdBosch** [comment]
Dit zit zo in het aanleverbesluit. Om deze ook als opsomming op te nemen, moet dit in Word als opsomming worden opgenomen:

![afbeelding](https://user-images.githubusercontent.com/27193836/124095088-a62f6300-da59-11eb-9567-26b5310fb026.png)
