### ISSUE TITLE
Alde Feanen: nota v. toelichting, paragraaf 4.2.1, de voetnoot in de titel is gek verwerkt, kan dit aangepast worden?

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#39]
![image](https://user-images.githubusercontent.com/86712182/124144429-3f776d00-da8c-11eb-877a-f07bef0eee84.png)

**Comment by HermanAssink** [comment]
Een voetnoot in/bij de kop wordt in de DSO Viewer op dezelfde manier weergeven, namelijk achter de koptekst. In PlanoView kan dit niet anders, misschien wel in de DSO viewer.

**Comment by KevinvdBosch** [comment]
Issue is al naar done versleept. Bij deze gesloten
