### ISSUE TITLE
Bijschrift bij afbeelding niet juist gepositioneerd

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/Natura2000inDSO#4]
Voorbeeld: Bijlage bij Naardermeer

**Comment by KevinvdBosch** [comment]
Was een bug bij het inlezen van de afbeelding. Bug is verholpen en afbeelding staat nu op de juiste positie

**Comment by RoderikTukker** [comment]
Afbeelding staat momenteel op de juiste positie met onderschrift.
![image](https://user-images.githubusercontent.com/86712182/124097691-1808ac00-da5c-11eb-8f78-8cfa32b43d02.png)
