### ISSUE TITLE
Bijlagen: Bijlage A plaatje ontbreekt - Groote Wielen

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Natura2000inDSO#41]
Het plaatje in bijlage A is niet meegekomen. In Word lijkt dit ook geen standaard PNG te zijn. Dit moet wel voor STOP.

**Comment by zoeheerema** [comment]
Plaatje van bijlage A is opnieuw toegevoegd, dit keer als PNG.

**Comment by KevinvdBosch** [comment]
plaatje is verwerkt
