### ISSUE TITLE
Opschrift: Datum aanwijzingsbesluit klopt niet + opmaak - Duinen Ameland

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#45]
De dubbele punt achter het woord ''van'' moet worden verwijderd zodat de hyperlink een geheel word. Datum aanwijzingsbesluit klopt niet. 3 januari moet 30 januari worden.

**Comment by KevinvdBosch** [comment]
Om de hyperlink als 1 geheel weer te geven, dient deze in het sjabloon aangemaakt te worden met de daarvoor gemaakte knop in het omgevingswet menu. Word slaat dit anders op een vreemde manier op die zeer moeilijk uit te lezen is.

![afbeelding](https://user-images.githubusercontent.com/27193836/124605210-f6e4f880-de6b-11eb-97b1-f53d435434e5.png)
