### ISSUE TITLE
Voetnoot fout - Van Oordts Merksen

### ISSUE THREAD

**Issue by zoeheerema** [IDgis/Natura2000inDSO#56]
Paragraaf 4.2.1 Habitatrichtlijn  (bijlage I [note 13 Bijlagen I en II … voetnoot fout, zat ook in eerdere aanwijzingsbesluiten, voetnoot volg ook direct. In het origineel staat (bijlage I¹³)

**Comment by RoderikTukker** [comment]
Herman liet mij weten dat dit geen probleem zal zijn.
![image](https://user-images.githubusercontent.com/86712182/125301232-1330db80-e32b-11eb-9ae6-cdfc84166167.png)
