### ISSUE TITLE
Bijlage C - Tekst en deeplink verkeerd opgemaakt - Sneekermeergebied

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Natura2000inDSO#62]
Vanaf bijlage C gaat er iets mis met de opmaak. Er lijken een aantal hoofdstukken zonder tekst toe te zijn gevoegd in het Word document. Hierdoor ziet dit er ook vreemd uit in de viewer.

![afbeelding](https://user-images.githubusercontent.com/27193836/125241410-ad712f00-e2eb-11eb-9eb4-f3533c545d0b.png)
--
![afbeelding](https://user-images.githubusercontent.com/27193836/125241469-c548b300-e2eb-11eb-8160-ffdcb19af4c9.png)

**Comment by zoeheerema** [comment]
Aangepast. Stonden inderdaad verschillende kopjes/hoofdstukken in de opmaak onder bijlage c zonder tekst. Deze zijn verwijderd.

**Comment by KevinvdBosch** [comment]
nieuwe versie staat klaar. Lijkt nu goed te zijn
