### ISSUE TITLE
Aanduiding voetnoten begint met "1 NOTE 1:" - hoort dit?

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#63]

**Comment by KevinvdBosch** [comment]
Het eerste nummer is het nummer van de voetnoot zoals onze viewer deze maakt. Die begint bij iedere paragraaf weer bij 1. Het deel ``NOTE 1:`` is visueel voor de viewer toegevoegd, zodat ook de referentie in Word gecontroleerd kan worden. Dit zal niet in het DSO opgenomen worden.
