### ISSUE TITLE
4.3.1. Habitattypen (bijlage I) - Xa & Xb worden niet als superscript weergeven - in het aanleverbestand wel

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#65]

**Comment by KevinvdBosch** [comment]
In het aanleverbestand zijn deze ook niet als superscript opgenomen. Alleen de grootte van het lettertype is aangepast, zodat het superscript lijkt.
![afbeelding](https://user-images.githubusercontent.com/27193836/125438844-450f2b84-ca0e-49f1-805a-29356e5f9699.png)

![afbeelding](https://user-images.githubusercontent.com/27193836/125438882-bdaa0b55-6be3-4987-9709-94f0129e3864.png)
