### ISSUE TITLE
Paragraaf 4.2.1 - de tabeluitlijning loopt scheef, is hier iets aan te doen?

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#81]

**Comment by KevinvdBosch** [comment]
In Word zijn dit losse tabellen die ook los opgemaakt zijn. Om die uit te lijnen moeten ze in Word ook precies gelijk uitgelijnd zijn

**Comment by RoderikTukker** [comment]
In dit geval zijn de tabellen in Word ook precies uitgelijnd, maar in de viewer komen ze er juist scheef uit.

![image](https://user-images.githubusercontent.com/86712182/125457381-fe4384cb-9ff7-4e22-912c-f69be87f2771.png)

**Comment by KevinvdBosch** [comment]
Het is wel erg lastig uitlijnen. Er is niet af te leiden welke tabellen hetzelfde uitgelijnd dienen te worden. Zo op het oog ziet het er in Word gelijk uit, terwijl er onder water toch een verschil is hoe het opgeslagen wordt:

![afbeelding](https://user-images.githubusercontent.com/27193836/125465164-6c0efe1b-d346-4a76-b244-f7ee145c6383.png)


![afbeelding](https://user-images.githubusercontent.com/27193836/125465197-fd568568-da97-4d2f-ad63-1adbf773198d.png)

Ik ga nog even kijken of er een andere manier is, waardoor de uitlijning er toch gelijk uit kan zien

**Comment by HermanAssink** [comment]
Uitlijning tabellen is verbeterd.
