### ISSUE TITLE
Drents-Friese Wold - opmaak van alle kopjes klopt niet en lopen door elkaar heen

### ISSUE THREAD

**Issue by RoderikTukker** [IDgis/Natura2000inDSO#86]
Het sjabloon is wel correct toegepast en de validatie heeft geen fouten aangegeven.
![image](https://user-images.githubusercontent.com/86712182/126132990-c24354a6-d033-49b3-b209-029397d854c3.png)

**Comment by KevinvdBosch** [comment]
Er zitten wat fouten in de opmaak, waardoor de weergave zo gegenereerd wordt:

- De titel is niet opgemaakt als OP_Officieletitel, maar als OP_Titel: 
![afbeelding](https://user-images.githubusercontent.com/27193836/126135111-ed84ac38-1033-4b4c-acc6-15b39143e3a1.png)
- Op meerdere plaatsen is tussen het nummer van de (sub)paragraaf en het opschrift geen spatie toegevoegd, waardoor de nummering verkeer afgelezen wordt: 
![afbeelding](https://user-images.githubusercontent.com/27193836/126135319-e7c05dcd-42c6-4eb5-a2ae-adf759583ed5.png)
- Bij de bijlagen zijn de hoofdstukken (Bijlage A en B) opgemaakt als "Bijlage bij toelichting" in plaats van als hoofdstuk onder de bijlagen: 
![afbeelding](https://user-images.githubusercontent.com/27193836/126135777-28d93771-0ec3-42bc-91d5-93dd992c8f81.png)




Door niet consistent gebruik van de indeling en opmaak kan de structuur niet goed worden afgeleid.
