### ISSUE TITLE
Vet gedrukt niet goed verwerkt in viewer

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/Natura2000inDSO#9]
Bij Naardermeer en Drentse Aa is op meerdere plekken het attribuut "vet" niet goed verwerkt. Het komt zowel voor dat iets ten onrechte vet gedrukt in de viewer wordt weregegeven als dat iets niet vet gedrukt in de viewer wordt weergegeven terwijl dat wel vet staat weergegeven in het brondocument.

**Comment by KevinvdBosch** [comment]
Was een bug in de software waarbij ten onrechte iets als vet werd gemarkeerd. Bug is opgelost
